#! /bin/bash
# ********************************************************************************************* 
# IRA Istituto di Radioastronomia                                                                      
# "@(#) $Id: operatorInput,v 1.1 2010-07-26 14:39:32 a.orlati Exp $"
#
# This code is under GNU General Public Licence (GPL).                                              
#                                                                                                     
# Who                                when            What                                             
# Andrea Orlati(aorlati@ira.inaf.it) 26/07/2010      Creation                                  
#************************************************************************

xterm -geometry 130x25+200+200 -sb -title OperatorInput -e /bin/bash --login -c "sysTerm $1" &