#! /bin/bash
# ********************************************************************************************* 
# IRA Istituto di Radioastronomia                                                                      
#
# This code is under GNU General Public Licence (GPL).                                              
#                                                                                                     
# Who                                when            What                                             
# Andrea Orlati(aorlati@ira.inaf.it) 12/08/2010      Creation 
# Andrea Orlati(aorlati@ira.inaf.it)04/09/2013      switch --stop now available                                
#************************************************************************
#   NAME
# 
#   SYNOPSIS
# 
#   DESCRIPTION
#
#   FILES
#
#   ENVIRONMENT
#
#   RETURN VALUES
#
#   CAUTIONS
#
#   EXAMPLES
#
#   SEE ALSO
#
#   BUGS     
#

LONGOPTS=help,stop
SHORTOPTS=hs
CL_HELP=
CL_STOP=

function printUsage {
   echo "Start interactive console for the DISCOS system"
   echo ""
        echo "Usage: `basename $0` [OPTIONS]  "
        echo "Options: "
        echo "   -h | --help    prints this help"
        echo "   -s | --stop    close the console and all the user interface windows"
}

# This simply checks for the correctness of the command line
export POSIXLY_CORRECT=1

getopt -n `basename $0` -Q -u -a -l $LONGOPTS $SHORTOPTS "$@" || {
   printUsage
   exit
}

# Now let's parse the command line
set -- `getopt -u -a -l $LONGOPTS $SHORTOPTS "$@"`

for i
do
	case "$i" in
		-h) CL_HELP=true ;;
		--help) CL_HELP=true ;;
		-s) CL_STOP=true ;;
		--stop) CL_STOP=true ;;
		--)  break;;
	esac
	shift
done

# restore
export POSIXLY_CORRECT=
unset POSIXLY_CORRECT

if [ "$CL_HELP" ] ; then
   printUsage
   exit
fi

if [ "$CL_STOP" ] ; then
   killall -s SIGUSR1 -u $USER -q _tui_MedicinaMountTextClient
   killall -s SIGUSR1 -u $USER -q _tui_ObservatoryTextClient
   killall -s SIGUSR1 -u $USER -q _tui_AntennaBossTextClient
   killall -s SIGUSR1 -u $USER -q _tui_GenericBackendTextClient
   killall -s SIGUSR1 -u $USER -q _tui_ReceiversBossTextClient
   killall -s SIGUSR1 -u $USER -q _tui_SchedulerTextClient
   killall -s SIGUSR1 -u $USER -q _tui_MinorServoBossTextClient 

   #close the operator input
   pkill -SIGUSR1 -u $USER -f _tui_SysTerm
   #close the logging display client 
   pkill -SIGUSR1 -f -n -u $USER _gui_customLoggingClient
   exit
fi

xterm -geometry 60x17+929+20 +sb -title Scheduler -e /bin/bash --login -c _tui_SchedulerTextClient &
sleep 0.5s
xterm -geometry 72x30+-10+20 +sb -title Mount -e /bin/bash --login -c _tui_MedicinaMountTextClient &
sleep 0.5s
xterm -geometry 73x17+1293+254 +sb -title Observatory -e /bin/bash --login -c _tui_ObservatoryTextClient &
sleep 0.5s
xterm -geometry 82x32+430+20 +sb -title AntennaBoss -e /bin/bash --login -c _tui_AntennaBossTextClient &
sleep 0.5s
xterm -geometry 101x28+921-68 +sb -title TotalPower -e /bin/bash --login -c "_tui_GenericBackendTextClient BACKENDS/TotalPower" &
sleep 0.5s
xterm -geometry 101x28+1107-68 +sb -title XArcos -e /bin/bash --login -c "_tui_GenericBackendTextClient BACKENDS/XBackends" &
sleep 0.5s
xterm -geometry 152x20+-5+389 -sb -title OperatorInput -e /bin/bash --login -c "_tui_SysTerm" &
sleep 0.5s
xterm -geometry 60x22+1299+20 +sb -title Receivers -e /bin/bash --login -c "_tui_ReceiversBossTextClient" &
sleep 0.5s
_gui_customLoggingClient --geometry 4,686 &
sleep 0.5s
xterm -geometry 60x15+929+282 +sb -title MinorServo -e /bin/bash --login -c "_tui_MinorServoBossTextClient" &
#
# ___oOo___
