#!/bin/bash
if [[ $(id -u) -ne 0 ]] ; then echo "Script must be run as root" ; exit 1 ; fi
GMOCK=gmock-1.7.0
GMOCK_BASE_URL=https://googlemock.googlecode.com/files
BUILDDIR=build
PWD=`pwd`
TMPDIR=`mktemp -d`
cd $TMPDIR
wget $GMOCK_BASE_URL/$GMOCK.zip
unzip $GMOCK.zip
cd $GMOCK
export GMOCK_HOME=`pwd`
mkdir $BUILDDIR
cd $BUILDDIR
cmake ..
make
chmod a+x *.a
cp *.a /usr/local/lib
cd $GMOCK_HOME/include
cp -r gmock /usr/local/include
cd $GMOCK_HOME/gtest
mkdir $BUILDDIR
cd $BUILDDIR
cmake ..
make
chmod a+x *.a
cp *.a /usr/local/lib
cd $GMOCK_HOME/gtest/include
cp -r gtest /usr/local/include
cd $PWD
rm -rf $TMPDIR

