#ifndef ___NOTOALLRECEIEVERS_IDL__
#define ___NOTOALLRECEIEVERS_IDL__


#include <baci.idl>
#include <ComponentErrors.idl>
#include "GenericReceiver.idl"

#pragma prefix "alma"

module Receivers {

	/**
	* This module defines the interface of the receivers installed in Noto. The frontends available in Noto are, presently,
	* no M&C interfaces, the only devices we need to control are the cal noise diode, the phase cal tone and the synthesizer.
	* It appears to be safe to concentrate this capabilities in only one component for all the receivers.
	* @author <a href=mailto:a.orlati@ira.inaf.it>Andrea Orlati</a>
    * <br>
	* @copybrief Receivers::Receiver::status
	* the single bits of the status word assumed the following meaning:
	* @arg \c 0 LOCAL, set if the receiver is in remote and can be controlled remotely, error
	* @arg \c 1 VACUUMSENSOR, set if the vacuum sensor is turned on, status
	* @arg \c 2 VACUUMPUMPSTATUS, set if the vacuum pump is on, status
	* @arg \c 3 VACUUMPUMPFAULT, set if the vacuum pump is in fault state, warning
	* @arg \c 4 VACUUMVALVEOPEN, set if the vacuum valve i sopen, status
	* @arg \c 5 COOLHEADON, set if the cool head is turned on, status
	* @arg \c 6 COMPRESSORFAULT, set if the compressor is in fault state is turned on, error
	* @arg \c 7 NOISEMARK, set is the calibration diode is on, status
	* @arg \c 8 NOISEMARKERROR, set if the calibration mark should be and it is not, or viceversa, error
	* @arg \c 9 EXTNOISEMARK, set if the control of the calibration diode from external source is enabled, status
	* @arg \c 10 CONNECTIONERROR, set if an error was found during the comunication from/to the receiver, error
	* @arg \c 11 UNLOCKED, set if at least one of the local oscillator is not locked, error
	* @copybrief Receivers::CommonReceiverInterface::setLO 
	*/


    interface NotoAllReceivers : ACS::CharacteristicComponent, Receiver {
         
	};


};

#endif
