/*************************************************************************************************************** */
/* Osservatorio Astronomico di Cagliari - INAF                                                                     	        */
/* $Id: Holography.idl,v 1.1 2011-04-15 14:28:26 spoppi Exp $										                    */
/*                                                                                                      	        */
/* This code is under GNU General Public Licence (GPL).                                                 	        */
/*                                                                                                      	        */
/* Who                                 when            What                                              	        */
/* Sergio Poppi			 	26/03/2012	Creation                                          	        */

#ifndef _DFBINTERFACE_IDL
#define _DFBINTERFACE_IDL



#include <baci.idl>
#include <enumpropMACRO.idl>
#include "GenericBackend.idl"

#pragma prefix "alma"

module Backends  {

	/**
		The Digital Filter Banks mark 3 (DFB3) is  the digital backends
		dual-receiver system.
		These unit is  digital correlator for spectral, continuum and pulsar observations
		and provides both the power spectrum of each polarisation (Total Intensity)
		and the complex cross-spectrum (polarization).  
	*/


	interface DFB: GenericBackend
		{
			
			
			void	initialize (in string configuration) 	 raises (ComponentErrors::ComponentErrorsEx,BackendsErrors::BackendsErrorsEx);



		};






};


#endif

