// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6.5 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:381


#include "DFBInterfaceC.h"
#include "tao/AnyTypeCode/Null_RefCount_Policy.h"
#include "tao/AnyTypeCode/TypeCode_Constants.h"
#include "tao/AnyTypeCode/Alias_TypeCode_Static.h"
#include "tao/AnyTypeCode/Objref_TypeCode_Static.h"
#include "tao/AnyTypeCode/String_TypeCode_Static.h"
#include "tao/CDR.h"
#include "tao/Exception_Data.h"
#include "tao/Invocation_Adapter.h"
#include "tao/Object_T.h"
#include "tao/CDR.h"
#include "tao/AnyTypeCode/Any.h"
#include "tao/AnyTypeCode/Any_Impl_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/UB_String_Arguments.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "DFBInterfaceC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:73

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:60

// Traits specializations for Backends::DFB.

Backends::DFB_ptr
TAO::Objref_Traits<Backends::DFB>::duplicate (
    Backends::DFB_ptr p)
{
  return Backends::DFB::_duplicate (p);
}

void
TAO::Objref_Traits<Backends::DFB>::release (
    Backends::DFB_ptr p)
{
  ::CORBA::release (p);
}

Backends::DFB_ptr
TAO::Objref_Traits<Backends::DFB>::nil (void)
{
  return Backends::DFB::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Backends::DFB>::marshal (
    const Backends::DFB_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

// Function pointer for collocation factory initialization.
TAO::Collocation_Proxy_Broker * 
(*Backends__TAO_DFB_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  ) = 0;

// TAO_IDL - Generated from
// be/be_visitor_operation/operation_cs.cpp:78

void Backends::DFB::initialize (
    const char * configuration)
{
  if (!this->is_evaluated ())
    {
      ::CORBA::Object::tao_object_initialize (this);
    }
  
  if (this->the_TAO_DFB_Proxy_Broker_ == 0)
    {
      Backends_DFB_setup_collocation ();
    }
  
  TAO::Arg_Traits< void>::ret_val _tao_retval;
  TAO::Arg_Traits< ::CORBA::Char *>::in_arg_val _tao_configuration (configuration);
  
  TAO::Argument *_the_tao_operation_signature [] =
    {
      &_tao_retval,
      &_tao_configuration
    };
  
  static TAO::Exception_Data
  _tao_Backends_DFB_initialize_exceptiondata [] = 
    {
      {
        "IDL:alma/ComponentErrors/ComponentErrorsEx:1.0",
        ComponentErrors::ComponentErrorsEx::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , ComponentErrors::_tc_ComponentErrorsEx
#endif /* TAO_HAS_INTERCEPTORS */
      },
      
      {
        "IDL:alma/BackendsErrors/BackendsErrorsEx:1.0",
        BackendsErrors::BackendsErrorsEx::_alloc
#if TAO_HAS_INTERCEPTORS == 1
        , BackendsErrors::_tc_BackendsErrorsEx
#endif /* TAO_HAS_INTERCEPTORS */
      }
    };
  
  TAO::Invocation_Adapter _tao_call (
      this,
      _the_tao_operation_signature,
      2,
      "initialize",
      10,
      this->the_TAO_DFB_Proxy_Broker_
    );
  
  _tao_call.invoke (
      _tao_Backends_DFB_initialize_exceptiondata,
      2
    );
}

Backends::DFB::DFB (void)
 : the_TAO_DFB_Proxy_Broker_ (0)
{
  this->Backends_DFB_setup_collocation ();
}

void
Backends::DFB::Backends_DFB_setup_collocation ()
{
  if (::Backends__TAO_DFB_Proxy_Broker_Factory_function_pointer)
    {
      this->the_TAO_DFB_Proxy_Broker_ =
        ::Backends__TAO_DFB_Proxy_Broker_Factory_function_pointer (this);
    }
  
  this->Backends_GenericBackend_setup_collocation ();
}

Backends::DFB::~DFB (void)
{}

void 
Backends::DFB::_tao_any_destructor (void *_tao_void_pointer)
{
  DFB *_tao_tmp_pointer =
    static_cast<DFB *> (_tao_void_pointer);
  ::CORBA::release (_tao_tmp_pointer);
}

Backends::DFB_ptr
Backends::DFB::_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<DFB>::narrow (
        _tao_objref,
        "IDL:alma/Backends/DFB:1.0",
        Backends__TAO_DFB_Proxy_Broker_Factory_function_pointer
      );
}

Backends::DFB_ptr
Backends::DFB::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref
  )
{
  return
    TAO::Narrow_Utils<DFB>::unchecked_narrow (
        _tao_objref,
        "IDL:alma/Backends/DFB:1.0",
        Backends__TAO_DFB_Proxy_Broker_Factory_function_pointer
      );
}

Backends::DFB_ptr
Backends::DFB::_duplicate (DFB_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  
  return obj;
}

void
Backends::DFB::_tao_release (DFB_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Backends::DFB::_is_a (const char *value)
{
  if (
      !ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/ACSComponent:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/CharacteristicModel:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/ACS/CharacteristicComponent:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/bulkdata/BulkDataSender:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/Management/CommandInterpreter:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/Backends/GenericBackend:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:alma/Backends/DFB:1.0"
        ) ||
      !ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        )
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return this->::CORBA::Object::_is_a (value);
    }
}

const char* Backends::DFB::_interface_repository_id (void) const
{
  return "IDL:alma/Backends/DFB:1.0";
}

::CORBA::Boolean
Backends::DFB::marshal (TAO_OutputCDR &cdr)
{
  return (cdr << this);
}

// TAO_IDL - Generated from
// be/be_visitor_typecode/objref_typecode.cpp:76

static TAO::TypeCode::Objref<char const *,
                             TAO::Null_RefCount_Policy>
  _tao_tc_Backends_DFB (
    ::CORBA::tk_objref,
    "IDL:alma/Backends/DFB:1.0",
    "DFB");
  
namespace Backends
{
  ::CORBA::TypeCode_ptr const _tc_DFB =
    &_tao_tc_Backends_DFB;
}



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_cs.cpp:51
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  template<>
  ::CORBA::Boolean
  Any_Impl_T<Backends::DFB>::to_object (
      ::CORBA::Object_ptr &_tao_elem
    ) const
  {
    _tao_elem = ::CORBA::Object::_duplicate (this->value_);
    return true;
  }
}
TAO_END_VERSIONED_NAMESPACE_DECL



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Backends
{
  
  
  /// Copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      DFB_ptr _tao_elem)
  {
    DFB_ptr _tao_objptr =
      DFB::_duplicate (_tao_elem);
    _tao_any <<= &_tao_objptr;
  }
  
  /// Non-copying insertion.
  void
  operator<<= (
      ::CORBA::Any &_tao_any,
      DFB_ptr *_tao_elem)
  {
    TAO::Any_Impl_T<DFB>::insert (
        _tao_any,
        DFB::_tao_any_destructor,
        _tc_DFB,
        *_tao_elem)
  }
  
  ::CORBA::Boolean
  operator>>= (
      const ::CORBA::Any &_tao_any,
      DFB_ptr &_tao_elem)
  {
    return
      TAO::Any_Impl_T<DFB>::extract (
          _tao_any,
          DFB::_tao_any_destructor,
          _tc_DFB,
          _tao_elem)
  }
}

#else

TAO_BEGIN_VERSIONED_NAMESPACE_DECL



/// Copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Backends::DFB_ptr _tao_elem)
{
  Backends::DFB_ptr _tao_objptr =
    Backends::DFB::_duplicate (_tao_elem);
  _tao_any <<= &_tao_objptr;
}

/// Non-copying insertion.
void
operator<<= (
    ::CORBA::Any &_tao_any,
    Backends::DFB_ptr *_tao_elem)
{
  TAO::Any_Impl_T<Backends::DFB>::insert (
      _tao_any,
      Backends::DFB::_tao_any_destructor,
      Backends::_tc_DFB,
      *_tao_elem);
}

::CORBA::Boolean
operator>>= (
    const ::CORBA::Any &_tao_any,
    Backends::DFB_ptr &_tao_elem)
{
  return
    TAO::Any_Impl_T<Backends::DFB>::extract (
        _tao_any,
        Backends::DFB::_tao_any_destructor,
        Backends::_tc_DFB,
        _tao_elem);
}

TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_cs.cpp:63

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

::CORBA::Boolean operator<< (
    TAO_OutputCDR &strm,
    const Backends::DFB_ptr _tao_objref)
{
  ::CORBA::Object_ptr _tao_corba_obj = _tao_objref;
  return (strm << _tao_corba_obj);
}

::CORBA::Boolean operator>> (
    TAO_InputCDR &strm,
    Backends::DFB_ptr &_tao_objref)
{
  ::CORBA::Object_var obj;
  
  if (!(strm >> obj.inout ()))
    {
      return false;
    }
  
  typedef ::Backends::DFB RHS_SCOPED_NAME;
  
  // Narrow to the right type.
  _tao_objref =
    TAO::Narrow_Utils<RHS_SCOPED_NAME>::unchecked_narrow (
        obj.in (),
        Backends__TAO_DFB_Proxy_Broker_Factory_function_pointer
      );
    
  return true;
}

TAO_END_VERSIONED_NAMESPACE_DECL



