// -*- C++ -*-
//
// $Id$

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler v1.6.5 ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:135

#ifndef _TAO_IDL____OBJECT_DFBINTERFACEC_H_
#define _TAO_IDL____OBJECT_DFBINTERFACEC_H_


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/AnyTypeCode/AnyTypeCode_methods.h"
#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Objref_VarOut_T.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "baciC.h"
#include "enumpropMACROC.h"
#include "GenericBackendC.h"

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from 
// be/be_visitor_root/root_ch.cpp:62
TAO_BEGIN_VERSIONED_NAMESPACE_DECL



namespace TAO
{
  class Collocation_Proxy_Broker;
  template<typename T> class Narrow_Utils;
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:49

namespace Backends
{
  
  // TAO_IDL - Generated from
  // be/be_interface.cpp:644

#if !defined (_BACKENDS_DFB__VAR_OUT_CH_)
#define _BACKENDS_DFB__VAR_OUT_CH_
  
  class DFB;
  typedef DFB *DFB_ptr;
  
  typedef
    TAO_Objref_Var_T<
        DFB
      >
    DFB_var;
  
  typedef
    TAO_Objref_Out_T<
        DFB
      >
    DFB_out;

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:54

#if !defined (_BACKENDS_DFB_CH_)
#define _BACKENDS_DFB_CH_
  
  class  DFB
    : public virtual ::Backends::GenericBackend
  {
  public:
    friend class TAO::Narrow_Utils<DFB>;
    typedef DFB_ptr _ptr_type;
    typedef DFB_var _var_type;
    typedef DFB_out _out_type;
    
    // The static operations.
    static DFB_ptr _duplicate (DFB_ptr obj);
    
    static void _tao_release (DFB_ptr obj);
    
    static DFB_ptr _narrow (::CORBA::Object_ptr obj);
    static DFB_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static DFB_ptr _nil (void)
    {
      return static_cast<DFB_ptr> (0);
    }
    
    static void _tao_any_destructor (void *);
    
    // TAO_IDL - Generated from
    // be/be_visitor_operation/operation_ch.cpp:46
    
    virtual void initialize (
        const char * configuration);
    
    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:216
    
    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  private:
    TAO::Collocation_Proxy_Broker *the_TAO_DFB_Proxy_Broker_;
  
  protected:
    // Concrete interface only.
    DFB (void);
    
    // These methods travese the inheritance tree and set the
    // parents piece of the given class in the right mode.
    virtual void Backends_DFB_setup_collocation (void);
    
    // Concrete non-local interface only.
    DFB (
        IOP::IOR *ior,
        TAO_ORB_Core *orb_core = 0);
    
    // Non-local interface only.
    DFB (
        TAO_Stub *objref,
        ::CORBA::Boolean _tao_collocated = false,
        TAO_Abstract_ServantBase *servant = 0,
        TAO_ORB_Core *orb_core = 0);
    
    virtual ~DFB (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    DFB (const DFB &);
    
    void operator= (const DFB &);
  };

#endif /* end #if !defined */
  
  // TAO_IDL - Generated from
  // be/be_visitor_typecode/typecode_decl.cpp:49
  
  extern  ::CORBA::TypeCode_ptr const _tc_DFB;

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:78

} // module Backends

// Proxy Broker Factory function pointer declarations.

// TAO_IDL - Generated from
// be/be_visitor_root/root.cpp:139

extern 
TAO::Collocation_Proxy_Broker *
(*Backends__TAO_DFB_Proxy_Broker_Factory_function_pointer) (
    ::CORBA::Object_ptr obj
  );

// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:64

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_BACKENDS_DFB__TRAITS_)
#define _BACKENDS_DFB__TRAITS_
  
  template<>
  struct  Objref_Traits< ::Backends::DFB>
  {
    static ::Backends::DFB_ptr duplicate (
        ::Backends::DFB_ptr p
      );
    static void release (
        ::Backends::DFB_ptr p
      );
    static ::Backends::DFB_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::Backends::DFB_ptr p,
        TAO_OutputCDR & cdr
      );
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_interface/any_op_ch.cpp:54



#if defined (ACE_ANY_OPS_USE_NAMESPACE)

namespace Backends
{
   void operator<<= ( ::CORBA::Any &, DFB_ptr); // copying
   void operator<<= ( ::CORBA::Any &, DFB_ptr *); // non-copying
   ::CORBA::Boolean operator>>= (const ::CORBA::Any &, DFB_ptr &);
}

#else


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 void operator<<= (::CORBA::Any &, Backends::DFB_ptr); // copying
 void operator<<= (::CORBA::Any &, Backends::DFB_ptr *); // non-copying
 ::CORBA::Boolean operator>>= (const ::CORBA::Any &, Backends::DFB_ptr &);
TAO_END_VERSIONED_NAMESPACE_DECL



#endif

// TAO_IDL - Generated from
// be/be_visitor_interface/cdr_op_ch.cpp:55

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

 ::CORBA::Boolean operator<< (TAO_OutputCDR &, const Backends::DFB_ptr );
 ::CORBA::Boolean operator>> (TAO_InputCDR &, Backends::DFB_ptr &);

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1226
#if defined (__ACE_INLINE__)
#include "DFBInterfaceC.inl"
#endif /* defined INLINE */

#endif /* ifndef */


