// -*- C++ -*-
//
// $Id: XBackendsErrorsS.h,v 1.1 2010/06/21 09:08:59 bliliana Exp $

// ****  Code generated by the The ACE ORB (TAO) IDL Compiler ****
// TAO and the TAO IDL Compiler have been developed by:
//       Center for Distributed Object Computing
//       Washington University
//       St. Louis, MO
//       USA
//       http://www.cs.wustl.edu/~schmidt/doc-center.html
// and
//       Distributed Object Computing Laboratory
//       University of California at Irvine
//       Irvine, CA
//       USA
//       http://doc.ece.uci.edu/
// and
//       Institute for Software Integrated Systems
//       Vanderbilt University
//       Nashville, TN
//       USA
//       http://www.isis.vanderbilt.edu/
//
// Information about TAO is available at:
//     http://www.cs.wustl.edu/~schmidt/TAO.html

// TAO_IDL - Generated from
// be/be_codegen.cpp:487

#ifndef _TAO_IDL____OBJECT_XBACKENDSERRORSS_H_
#define _TAO_IDL____OBJECT_XBACKENDSERRORSS_H_


#include "XBackendsErrorsC.h"
#include "acserrS.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:49

namespace POA_ACSErr
{
  

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:80

} // module ACSErr

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:49

namespace POA_XBackendsErrors
{
  

// TAO_IDL - Generated from
// be/be_visitor_module/module_sh.cpp:80

} // module XBackendsErrors

// TAO_IDL - Generated from 
// be/be_codegen.cpp:1290


#if defined (__ACE_INLINE__)
#include "XBackendsErrorsS.inl"
#endif /* defined INLINE */

#endif /* ifndef */

