/* *******************************************************************/
/* OAC Osservatorio Astronomico di Cagliari                          */
/*                                                                   */
/* This code is under GNU General Public Licence (GPL).              */
/*                                                                   */
/* Who                                when        what               */
/* Carlo Migoni (migoni@oa-cagliari.inaf.it)  10/07/2013  Creation   */
/*********************************************************************/

#ifndef _MinorServoBOSS_IDL_

#define _MinorServoBOSS_IDL_

#include <baci.idl>
#include <ManagmentDefinitions.idl>

#pragma prefix "alma"

module MinorServo {

	/**
	* This component is the supervisor of the Minor Servo subsystem.
     	* It will be used to control the entire minor servo during an observation.
	* @author <a href=mailto:migoni@oa-cagliari.inf.it>Carlo Migoni</a>,
 	* Osservatorio Astronomico di Cagliari, Italia
 	* <br> 
	*/ 
	interface NotoMinorServoBoss: ACS::CharacteristicComponent, Management::CommandInterpreter, Management::Subsystem {

        	/**
		* This method can be called in order to disable the MinorServo refresh.
		* @throw CORBA::SystemException 
		*/
		void msOff();
		
		/**
		* This method can be called in order to enable the active surface refresh.
		* @throw CORBA::SystemException 
		*/		
		void msOn();
	};
};

#endif
