#! /bin/bash
# ***********************************************************************
# Who                                           when            What
# Andrea Orlati(andrea.orlati@inaf.it)          22/05/2020      Creation
#************************************************************************


export ACS_LOG_STDOUT=11
_ctc $1
