# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibrationToolClient.ui'
#
# Created: Fri Sep 21 03:37:11 2012
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from customwidgets import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CalibrationToolDialog(object):
    def setupUi(self, CalibrationToolDialog):
        CalibrationToolDialog.setObjectName(_fromUtf8("CalibrationToolDialog"))
        CalibrationToolDialog.resize(910, 661)
        self.buttonBox = QtGui.QDialogButtonBox(CalibrationToolDialog)
        self.buttonBox.setGeometry(QtCore.QRect(710, 590, 81, 31))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.verticalLayoutWidget = QtGui.QWidget(CalibrationToolDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 100, 661, 521))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.qwtPlot_datay = PlotProperty(self.verticalLayoutWidget)
        self.qwtPlot_datay.setFrameShape(QtGui.QFrame.VLine)
        self.qwtPlot_datay.setObjectName(_fromUtf8("qwtPlot_datay"))
        self.verticalLayout.addWidget(self.qwtPlot_datay)
        self.qwtPlot_datax = PlotProperty(self.verticalLayoutWidget)
        self.qwtPlot_datax.setObjectName(_fromUtf8("qwtPlot_datax"))
        self.verticalLayout.addWidget(self.qwtPlot_datax)
        self.label = QtGui.QLabel(CalibrationToolDialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 60, 18))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(CalibrationToolDialog)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 60, 18))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(CalibrationToolDialog)
        self.label_3.setGeometry(QtCore.QRect(500, 20, 60, 18))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.plainTextEdit_project = QtGui.QPlainTextEdit(CalibrationToolDialog)
        self.plainTextEdit_project.setGeometry(QtCore.QRect(18, 40, 210, 51))
        self.plainTextEdit_project.setObjectName(_fromUtf8("plainTextEdit_project"))
        self.plainTextEdit_filename = QtGui.QPlainTextEdit(CalibrationToolDialog)
        self.plainTextEdit_filename.setGeometry(QtCore.QRect(497, 40, 401, 51))
        self.plainTextEdit_filename.setObjectName(_fromUtf8("plainTextEdit_filename"))
        self.plainTextEdit_observer = QtGui.QPlainTextEdit(CalibrationToolDialog)
        self.plainTextEdit_observer.setGeometry(QtCore.QRect(240, 40, 241, 51))
        self.plainTextEdit_observer.setMouseTracking(True)
        self.plainTextEdit_observer.setObjectName(_fromUtf8("plainTextEdit_observer"))
        self.formFrame = QtGui.QFrame(CalibrationToolDialog)
        self.formFrame.setGeometry(QtCore.QRect(710, 100, 191, 241))
        self.formFrame.setFrameShape(QtGui.QFrame.Box)
        self.formFrame.setObjectName(_fromUtf8("formFrame"))
        self.formLayout_2 = QtGui.QFormLayout(self.formFrame)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(0, QtGui.QFormLayout.LabelRole, spacerItem)
        self.textLabel = QtGui.QLabel(self.formFrame)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Vera Sans"))
        font.setWeight(75)
        font.setBold(True)
        self.textLabel.setFont(font)
        self.textLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel.setObjectName(_fromUtf8("textLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.SpanningRole, self.textLabel)
        self.fluxLabel = QtGui.QLabel(self.formFrame)
        self.fluxLabel.setObjectName(_fromUtf8("fluxLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.fluxLabel)
        self.fluxLineEdit = QtGui.QLineEdit(self.formFrame)
        self.fluxLineEdit.setMaximumSize(QtCore.QSize(94, 16777215))
        self.fluxLineEdit.setReadOnly(True)
        self.fluxLineEdit.setObjectName(_fromUtf8("fluxLineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.fluxLineEdit)
        self.fluxLabel_2 = QtGui.QLabel(self.formFrame)
        self.fluxLabel_2.setObjectName(_fromUtf8("fluxLabel_2"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.fluxLabel_2)
        self.fluxLineEdit_2 = QtGui.QLineEdit(self.formFrame)
        self.fluxLineEdit_2.setMinimumSize(QtCore.QSize(94, 0))
        self.fluxLineEdit_2.setReadOnly(True)
        self.fluxLineEdit_2.setObjectName(_fromUtf8("fluxLineEdit_2"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.fluxLineEdit_2)
        spacerItem1 = QtGui.QSpacerItem(20, 70, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(4, QtGui.QFormLayout.LabelRole, spacerItem1)
        self.deviceIdLabel = QtGui.QLabel(self.formFrame)
        self.deviceIdLabel.setObjectName(_fromUtf8("deviceIdLabel"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.deviceIdLabel)
        self.deviceIdLineEdit = QtGui.QLineEdit(self.formFrame)
        self.deviceIdLineEdit.setMaximumSize(QtCore.QSize(94, 16777215))
        self.deviceIdLineEdit.setReadOnly(True)
        self.deviceIdLineEdit.setObjectName(_fromUtf8("deviceIdLineEdit"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.deviceIdLineEdit)
        self.scanIdLabel = QtGui.QLabel(self.formFrame)
        self.scanIdLabel.setObjectName(_fromUtf8("scanIdLabel"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.FieldRole, self.scanIdLabel)
        self.scanIdLineEdit = QtGui.QLineEdit(self.formFrame)
        self.scanIdLineEdit.setMaximumSize(QtCore.QSize(94, 16777215))
        self.scanIdLineEdit.setReadOnly(True)
        self.scanIdLineEdit.setObjectName(_fromUtf8("scanIdLineEdit"))
        self.formLayout_2.setWidget(9, QtGui.QFormLayout.LabelRole, self.scanIdLineEdit)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(10, QtGui.QFormLayout.LabelRole, spacerItem2)
        self.subscanIdLineEdit = QtGui.QLineEdit(self.formFrame)
        self.subscanIdLineEdit.setMaximumSize(QtCore.QSize(94, 16777215))
        self.subscanIdLineEdit.setReadOnly(True)
        self.subscanIdLineEdit.setObjectName(_fromUtf8("subscanIdLineEdit"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.LabelRole, self.subscanIdLineEdit)
        self.scanIdLabel_2 = QtGui.QLabel(self.formFrame)
        self.scanIdLabel_2.setObjectName(_fromUtf8("scanIdLabel_2"))
        self.formLayout_2.setWidget(11, QtGui.QFormLayout.FieldRole, self.scanIdLabel_2)
        self.frame = QtGui.QFrame(CalibrationToolDialog)
        self.frame.setGeometry(QtCore.QRect(710, 360, 191, 201))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setHorizontalSpacing(16)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_4)
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.frame)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.frame)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.FieldRole, self.label_8)
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_5)
        self.hpbwLineEdit = QtGui.QLineEdit(self.frame)
        self.hpbwLineEdit.setMaximumSize(QtCore.QSize(88, 16777215))
        self.hpbwLineEdit.setReadOnly(True)
        self.hpbwLineEdit.setObjectName(_fromUtf8("hpbwLineEdit"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.hpbwLineEdit)
        self.amplitudeLineEdit = QtGui.QLineEdit(self.frame)
        self.amplitudeLineEdit.setMaximumSize(QtCore.QSize(88, 16777215))
        self.amplitudeLineEdit.setReadOnly(True)
        self.amplitudeLineEdit.setObjectName(_fromUtf8("amplitudeLineEdit"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.amplitudeLineEdit)
        self.peakoffsetLineEdit = QtGui.QLineEdit(self.frame)
        self.peakoffsetLineEdit.setMaximumSize(QtCore.QSize(88, 16777215))
        self.peakoffsetLineEdit.setReadOnly(True)
        self.peakoffsetLineEdit.setObjectName(_fromUtf8("peakoffsetLineEdit"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.peakoffsetLineEdit)
        self.slopeLineEdit = QtGui.QLineEdit(self.frame)
        self.slopeLineEdit.setMaximumSize(QtCore.QSize(88, 16777215))
        self.slopeLineEdit.setReadOnly(True)
        self.slopeLineEdit.setObjectName(_fromUtf8("slopeLineEdit"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.slopeLineEdit)
        self.offsetLineEdit = QtGui.QLineEdit(self.frame)
        self.offsetLineEdit.setMaximumSize(QtCore.QSize(88, 16777215))
        self.offsetLineEdit.setReadOnly(True)
        self.offsetLineEdit.setObjectName(_fromUtf8("offsetLineEdit"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.offsetLineEdit)

        self.retranslateUi(CalibrationToolDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CalibrationToolDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CalibrationToolDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CalibrationToolDialog)

    def retranslateUi(self, CalibrationToolDialog):
        CalibrationToolDialog.setWindowTitle(QtGui.QApplication.translate("CalibrationToolDialog", "Calibration Tool Client", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Observer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.textLabel.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Source", None, QtGui.QApplication.UnicodeUTF8))
        self.fluxLabel.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.fluxLabel_2.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Flux", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceIdLabel.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Device Id", None, QtGui.QApplication.UnicodeUTF8))
        self.scanIdLabel.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Scan Id", None, QtGui.QApplication.UnicodeUTF8))
        self.scanIdLabel_2.setText(QtGui.QApplication.translate("CalibrationToolDialog", "SubScan Id", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("CalibrationToolDialog", "HPBW", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("CalibrationToolDialog", "PeakOffset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Slope", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Offset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Amplitude", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5
