# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibrationToolClient.ui'
#
# Created: Fri Dec 13 17:35:39 2013
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!
from customwidgets import *

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_CalibrationToolDialog(object):
    def setupUi(self, CalibrationToolDialog):
        CalibrationToolDialog.setObjectName(_fromUtf8("CalibrationToolDialog"))
        CalibrationToolDialog.resize(954, 572)
        self.label = QtGui.QLabel(CalibrationToolDialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 211, 18))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(CalibrationToolDialog)
        self.label_2.setGeometry(QtCore.QRect(240, 20, 241, 18))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(CalibrationToolDialog)
        self.label_3.setGeometry(QtCore.QRect(500, 20, 391, 18))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.plainTextEdit_project = QtGui.QPlainTextEdit(CalibrationToolDialog)
        self.plainTextEdit_project.setGeometry(QtCore.QRect(18, 40, 210, 51))
        self.plainTextEdit_project.setObjectName(_fromUtf8("plainTextEdit_project"))
        self.plainTextEdit_filename = QtGui.QPlainTextEdit(CalibrationToolDialog)
        self.plainTextEdit_filename.setGeometry(QtCore.QRect(527, 40, 401, 51))
        self.plainTextEdit_filename.setObjectName(_fromUtf8("plainTextEdit_filename"))
        self.plainTextEdit_observer = QtGui.QPlainTextEdit(CalibrationToolDialog)
        self.plainTextEdit_observer.setGeometry(QtCore.QRect(240, 40, 271, 51))
        self.plainTextEdit_observer.setMouseTracking(True)
        self.plainTextEdit_observer.setObjectName(_fromUtf8("plainTextEdit_observer"))
        self.formFrame = QtGui.QFrame(CalibrationToolDialog)
        self.formFrame.setGeometry(QtCore.QRect(560, 100, 371, 371))
        self.formFrame.setFrameShape(QtGui.QFrame.Box)
        self.formFrame.setObjectName(_fromUtf8("formFrame"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.formFrame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 408, 351))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.fluxLabel_3 = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fluxLabel_3.sizePolicy().hasHeightForWidth())
        self.fluxLabel_3.setSizePolicy(sizePolicy)
        self.fluxLabel_3.setMinimumSize(QtCore.QSize(100, 22))
        self.fluxLabel_3.setObjectName(_fromUtf8("fluxLabel_3"))
        self.gridLayout_3.addWidget(self.fluxLabel_3, 0, 0, 1, 1)
        self.nameLineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.nameLineEdit.setMinimumSize(QtCore.QSize(94, 22))
        self.nameLineEdit.setMaximumSize(QtCore.QSize(150, 26))
        self.nameLineEdit.setReadOnly(True)
        self.nameLineEdit.setObjectName(_fromUtf8("nameLineEdit"))
        self.gridLayout_3.addWidget(self.nameLineEdit, 0, 1, 1, 1)
        self.fluxLabel_4 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.fluxLabel_4.setMinimumSize(QtCore.QSize(100, 22))
        self.fluxLabel_4.setObjectName(_fromUtf8("fluxLabel_4"))
        self.gridLayout_3.addWidget(self.fluxLabel_4, 1, 0, 1, 1)
        self.fluxLineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.fluxLineEdit.setMinimumSize(QtCore.QSize(94, 22))
        self.fluxLineEdit.setMaximumSize(QtCore.QSize(150, 26))
        self.fluxLineEdit.setReadOnly(True)
        self.fluxLineEdit.setObjectName(_fromUtf8("fluxLineEdit"))
        self.gridLayout_3.addWidget(self.fluxLineEdit, 1, 1, 1, 1)
        self.deviceIdLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.deviceIdLabel.setMinimumSize(QtCore.QSize(100, 22))
        self.deviceIdLabel.setObjectName(_fromUtf8("deviceIdLabel"))
        self.gridLayout_3.addWidget(self.deviceIdLabel, 2, 0, 1, 1)
        self.deviceIdLineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.deviceIdLineEdit.setMinimumSize(QtCore.QSize(94, 22))
        self.deviceIdLineEdit.setMaximumSize(QtCore.QSize(150, 26))
        self.deviceIdLineEdit.setReadOnly(True)
        self.deviceIdLineEdit.setObjectName(_fromUtf8("deviceIdLineEdit"))
        self.gridLayout_3.addWidget(self.deviceIdLineEdit, 2, 1, 1, 1)
        self.scanIdLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.scanIdLabel.setMinimumSize(QtCore.QSize(100, 22))
        self.scanIdLabel.setObjectName(_fromUtf8("scanIdLabel"))
        self.gridLayout_3.addWidget(self.scanIdLabel, 3, 0, 1, 1)
        self.scanIdLineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.scanIdLineEdit.setMinimumSize(QtCore.QSize(94, 22))
        self.scanIdLineEdit.setMaximumSize(QtCore.QSize(150, 26))
        self.scanIdLineEdit.setReadOnly(True)
        self.scanIdLineEdit.setObjectName(_fromUtf8("scanIdLineEdit"))
        self.gridLayout_3.addWidget(self.scanIdLineEdit, 3, 1, 1, 1)
        self.scanIdLabel_2 = QtGui.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scanIdLabel_2.sizePolicy().hasHeightForWidth())
        self.scanIdLabel_2.setSizePolicy(sizePolicy)
        self.scanIdLabel_2.setMinimumSize(QtCore.QSize(94, 22))
        self.scanIdLabel_2.setObjectName(_fromUtf8("scanIdLabel_2"))
        self.gridLayout_3.addWidget(self.scanIdLabel_2, 4, 0, 1, 1)
        self.subscanIdLineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.subscanIdLineEdit.setMinimumSize(QtCore.QSize(94, 22))
        self.subscanIdLineEdit.setMaximumSize(QtCore.QSize(150, 26))
        self.subscanIdLineEdit.setReadOnly(True)
        self.subscanIdLineEdit.setObjectName(_fromUtf8("subscanIdLineEdit"))
        self.gridLayout_3.addWidget(self.subscanIdLineEdit, 4, 1, 1, 1)
        self.hpbw_label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.hpbw_label.setMinimumSize(QtCore.QSize(100, 22))
        self.hpbw_label.setObjectName(_fromUtf8("hpbw_label"))
        self.gridLayout_3.addWidget(self.hpbw_label, 5, 0, 1, 1)
        self.hpbwLineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.hpbwLineEdit.setMinimumSize(QtCore.QSize(94, 22))
        self.hpbwLineEdit.setMaximumSize(QtCore.QSize(150, 26))
        self.hpbwLineEdit.setReadOnly(True)
        self.hpbwLineEdit.setObjectName(_fromUtf8("hpbwLineEdit"))
        self.gridLayout_3.addWidget(self.hpbwLineEdit, 5, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_11.setMinimumSize(QtCore.QSize(100, 22))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 6, 0, 1, 1)
        self.amplitudeLineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.amplitudeLineEdit.setMinimumSize(QtCore.QSize(94, 22))
        self.amplitudeLineEdit.setMaximumSize(QtCore.QSize(150, 26))
        self.amplitudeLineEdit.setReadOnly(True)
        self.amplitudeLineEdit.setObjectName(_fromUtf8("amplitudeLineEdit"))
        self.gridLayout_3.addWidget(self.amplitudeLineEdit, 6, 1, 1, 1)
        self.peakOffsetLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.peakOffsetLabel.setMinimumSize(QtCore.QSize(100, 22))
        self.peakOffsetLabel.setObjectName(_fromUtf8("peakOffsetLabel"))
        self.gridLayout_3.addWidget(self.peakOffsetLabel, 7, 0, 1, 1)
        self.peakoffsetLineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.peakoffsetLineEdit.setMinimumSize(QtCore.QSize(94, 22))
        self.peakoffsetLineEdit.setMaximumSize(QtCore.QSize(150, 26))
        self.peakoffsetLineEdit.setReadOnly(True)
        self.peakoffsetLineEdit.setObjectName(_fromUtf8("peakoffsetLineEdit"))
        self.gridLayout_3.addWidget(self.peakoffsetLineEdit, 7, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_13.setMinimumSize(QtCore.QSize(100, 22))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 8, 0, 1, 1)
        self.slopeLineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.slopeLineEdit.setMinimumSize(QtCore.QSize(94, 22))
        self.slopeLineEdit.setMaximumSize(QtCore.QSize(150, 26))
        self.slopeLineEdit.setReadOnly(True)
        self.slopeLineEdit.setObjectName(_fromUtf8("slopeLineEdit"))
        self.gridLayout_3.addWidget(self.slopeLineEdit, 8, 1, 1, 1)
        self.offset_label = QtGui.QLabel(self.gridLayoutWidget_2)
        self.offset_label.setMinimumSize(QtCore.QSize(100, 22))
        self.offset_label.setObjectName(_fromUtf8("offset_label"))
        self.gridLayout_3.addWidget(self.offset_label, 9, 0, 1, 1)
        self.offsetLineEdit = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offsetLineEdit.sizePolicy().hasHeightForWidth())
        self.offsetLineEdit.setSizePolicy(sizePolicy)
        self.offsetLineEdit.setMinimumSize(QtCore.QSize(94, 22))
        self.offsetLineEdit.setMaximumSize(QtCore.QSize(150, 26))
        self.offsetLineEdit.setReadOnly(True)
        self.offsetLineEdit.setObjectName(_fromUtf8("offsetLineEdit"))
        self.gridLayout_3.addWidget(self.offsetLineEdit, 9, 1, 1, 1)
        self.recording = QtGui.QLineEdit(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recording.sizePolicy().hasHeightForWidth())
        self.recording.setSizePolicy(sizePolicy)
        self.recording.setMinimumSize(QtCore.QSize(0, 0))
        self.recording.setMaximumSize(QtCore.QSize(150, 16777215))
        self.recording.setAlignment(QtCore.Qt.AlignCenter)
        self.recording.setObjectName(_fromUtf8("recording"))
        self.gridLayout_3.addWidget(self.recording, 11, 1, 1, 1)
        self.BScanaxis = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.BScanaxis.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BScanaxis.sizePolicy().hasHeightForWidth())
        self.BScanaxis.setSizePolicy(sizePolicy)
        self.BScanaxis.setMinimumSize(QtCore.QSize(0, 0))
        self.BScanaxis.setMaximumSize(QtCore.QSize(150, 16777215))
        self.BScanaxis.setAlignment(QtCore.Qt.AlignCenter)
        self.BScanaxis.setObjectName(_fromUtf8("BScanaxis"))
        self.gridLayout_3.addWidget(self.BScanaxis, 10, 1, 1, 1)
        self.scanAxisLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.scanAxisLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.scanAxisLabel.setObjectName(_fromUtf8("scanAxisLabel"))
        self.gridLayout_3.addWidget(self.scanAxisLabel, 10, 0, 1, 1)
        self.recordingLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.recordingLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.recordingLabel.setObjectName(_fromUtf8("recordingLabel"))
        self.gridLayout_3.addWidget(self.recordingLabel, 11, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(CalibrationToolDialog)
        self.frame_2.setGeometry(QtCore.QRect(20, 100, 541, 431))
        self.frame_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_2.setFrameShadow(QtGui.QFrame.Plain)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout.addWidget(self.label_10)
        self.qwtPlot_datax = PlotProperty(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qwtPlot_datax.sizePolicy().hasHeightForWidth())
        self.qwtPlot_datax.setSizePolicy(sizePolicy)
        self.qwtPlot_datax.setMinimumSize(QtCore.QSize(500, 178))
        self.qwtPlot_datax.setMaximumSize(QtCore.QSize(500, 178))
        self.qwtPlot_datax.setObjectName(_fromUtf8("qwtPlot_datax"))
        self.verticalLayout.addWidget(self.qwtPlot_datax)
        self.qwtPlot_datay = PlotProperty(self.frame_2)
        self.qwtPlot_datay.setMinimumSize(QtCore.QSize(500, 178))
        self.qwtPlot_datay.setMaximumSize(QtCore.QSize(500, 178))
        self.qwtPlot_datay.setFrameShape(QtGui.QFrame.NoFrame)
        self.qwtPlot_datay.setObjectName(_fromUtf8("qwtPlot_datay"))
        self.verticalLayout.addWidget(self.qwtPlot_datay)
        self.label_9 = QtGui.QLabel(self.frame_2)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout.addWidget(self.label_9)
        self.frame = QtGui.QFrame(CalibrationToolDialog)
        self.frame.setGeometry(QtCore.QRect(560, 470, 371, 61))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.buttonBox = QtGui.QDialogButtonBox(self.frame)
        self.buttonBox.setGeometry(QtCore.QRect(0, 10, 401, 34))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setWhatsThis(_fromUtf8(""))
        self.buttonBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonBox.setAutoFillBackground(False)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))

        self.retranslateUi(CalibrationToolDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), CalibrationToolDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), CalibrationToolDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(CalibrationToolDialog)

    def retranslateUi(self, CalibrationToolDialog):
        CalibrationToolDialog.setWindowTitle(QtGui.QApplication.translate("CalibrationToolDialog", "Calibration Tool Client", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Project", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Observer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Filename", None, QtGui.QApplication.UnicodeUTF8))
        self.fluxLabel_3.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.fluxLabel_4.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Flux", None, QtGui.QApplication.UnicodeUTF8))
        self.deviceIdLabel.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Device Id", None, QtGui.QApplication.UnicodeUTF8))
        self.scanIdLabel.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Scan Id", None, QtGui.QApplication.UnicodeUTF8))
        self.scanIdLabel_2.setText(QtGui.QApplication.translate("CalibrationToolDialog", "SubScan Id", None, QtGui.QApplication.UnicodeUTF8))
        self.hpbw_label.setText(QtGui.QApplication.translate("CalibrationToolDialog", "HPBW(arcmim)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Amplitude (K)", None, QtGui.QApplication.UnicodeUTF8))
        self.peakOffsetLabel.setText(QtGui.QApplication.translate("CalibrationToolDialog", "PeakOffset(deg)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Slope", None, QtGui.QApplication.UnicodeUTF8))
        self.offset_label.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Offset (K)", None, QtGui.QApplication.UnicodeUTF8))
        self.recording.setText(QtGui.QApplication.translate("CalibrationToolDialog", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.BScanaxis.setText(QtGui.QApplication.translate("CalibrationToolDialog", "none", None, QtGui.QApplication.UnicodeUTF8))
        self.scanAxisLabel.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Scan Axis", None, QtGui.QApplication.UnicodeUTF8))
        self.recordingLabel.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Current Subscan", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("CalibrationToolDialog", "Last Subscan", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5
