/***************************************************************\
 *  Authors: 
 *      Giuseppe Carboni <giuseppe.carboni@inaf.it>
 *
 *  Created: Mon Mar 06 12:30:00 CEST 2023
 *  Last Modified: Mon Mar 06 12:30:00 CEST 2023
\***************************************************************/
#ifndef __SRTMINORSERVOBOSS_IDL__
#define __SRTMINORSERVOBOSS_IDL__

#include <MinorServoBoss.idl>
#include "SRTMinorServoCommon.idl"

#pragma prefix "alma"

module MinorServo
{
    interface SRTMinorServoBoss: MinorServoBoss
    {
        readonly attribute ROSRTMinorServoFocalConfiguration current_configuration;
        readonly attribute Management::ROTBoolean simulation_enabled;
        readonly attribute ACS::ROdouble plc_time;
        readonly attribute ACS::ROstring plc_version;
        readonly attribute ROSRTMinorServoControlStatus control;
        readonly attribute Management::ROTBoolean power;
        readonly attribute Management::ROTBoolean emergency;
        readonly attribute ROSRTMinorServoGregorianCoverStatus gregorian_cover;
        readonly attribute ACS::ROdouble last_executed_command;

        void preset(in double elevation) raises (MinorServoErrors::MinorServoErrorsEx, ComponentErrors::ComponentErrorsEx);
    };
};

#endif
