/***************************************************************\
 *  Authors: 
 *      Giuseppe Carboni <giuseppe.carboni@inaf.it>
 *
 *  Created: Mon Mar 06 12:30:00 CEST 2023
 *  Last Modified: Mon Mar 06 12:30:00 CEST 2023
\***************************************************************/

#ifndef __SRTMINORSERVO_IDL__
#define __SRTMINORSERVO_IDL__

#include "SRTMinorServoCommon.idl"

#pragma prefix "alma"

module MinorServo
{
    interface SRTBaseMinorServo : ACS::CharacteristicComponent
    {
        readonly attribute Management::ROTBoolean enabled;
        readonly attribute ROSRTMinorServoCabinetStatus drive_cabinet_status;
        readonly attribute Management::ROTBoolean block;
        readonly attribute ROSRTMinorServoOperativeMode operative_mode;
        readonly attribute ACS::RObooleanSeq physical_axes_enabled;
        readonly attribute ACS::ROdoubleSeq physical_positions;
        readonly attribute ACS::ROlong virtual_axes;
        readonly attribute ACS::ROdoubleSeq virtual_positions;
        readonly attribute ACS::ROdoubleSeq virtual_offsets;
        readonly attribute ACS::ROdoubleSeq virtual_user_offsets;
        readonly attribute ACS::ROdoubleSeq virtual_system_offsets;
        readonly attribute Management::ROTBoolean in_use;
        readonly attribute ACS::ROstring current_setup;

        void status() raises (ComponentErrors::ComponentErrorsEx);
        void stow(in long stow_position) raises (ComponentErrors::ComponentErrorsEx, MinorServoErrors::MinorServoErrorsEx);
        void stop() raises (ComponentErrors::ComponentErrorsEx, MinorServoErrors::MinorServoErrorsEx);
        void preset(in ACS::doubleSeq coordinates) raises (ComponentErrors::ComponentErrorsEx, MinorServoErrors::MinorServoErrorsEx);
        void offset(in ACS::doubleSeq offsets) raises (ComponentErrors::ComponentErrorsEx, MinorServoErrors::MinorServoErrorsEx);
        ACS::doubleSeq getUserOffsets();
        void setUserOffset(in string axis_name, in double offset) raises (ComponentErrors::ComponentErrorsEx, MinorServoErrors::MinorServoErrorsEx);
        void clearUserOffsets() raises (ComponentErrors::ComponentErrorsEx, MinorServoErrors::MinorServoErrorsEx);
        ACS::doubleSeq getSystemOffsets();
        void setSystemOffset(in string axis_name, in double offset) raises (ComponentErrors::ComponentErrorsEx, MinorServoErrors::MinorServoErrorsEx);
        void clearSystemOffsets() raises (ComponentErrors::ComponentErrorsEx, MinorServoErrors::MinorServoErrorsEx);

        void setup(in string configuration) raises (ComponentErrors::ComponentErrorsEx, MinorServoErrors::MinorServoErrorsEx);
        void getAxesInfo(out ACS::stringSeq axes_names, out ACS::stringSeq axes_units) raises (ComponentErrors::ComponentErrorsEx);
        ACS::doubleSeq calcCoordinates(in double elevation);

    };

    interface SRTGenericMinorServo : SRTBaseMinorServo
    {
    };

    interface SRTProgramTrackMinorServo : SRTBaseMinorServo
    {
        void programTrack(in long trajectory_id, in long point_id, in double start_time, in ACS::doubleSeq coordinates) raises (ComponentErrors::ComponentErrorsEx);
    };
};

#endif
