#! /bin/bash
# ********************************************************************************************* 
# IRA Istituto di Radioastronomia                                                                      
# "@(#) $Id: mountTui,v 1.2 2011-06-01 18:25:35 a.orlati Exp $"
#
# This code is under GNU General Public Licence (GPL).                                              
#                                                                                                     
# Who                                when            What                                             
# Andrea Orlati(aorlati@ira.inaf.it) 07/05/2010      Creation                                  
#************************************************************************

xterm -geometry 100x37+0+0 +sb -title Mount -e /bin/bash --login -c _tui_SRTMountTextClient &