#ifndef _BULKDATAZMQ_RECEIVER_IDL_
#define _BULKDATAZMQ_RECEIVER_IDL_

/*******************************************************************************
 * "@(#)"
 *
 * who            when      what
 * --------       --------  ----------------------------------------------
 * Andrea Orlati  03/04/26  created
 */

#include <baci.idl>
#include "ACSBulkDataError.idl"
//#include "ACSBulkDataStatus.idl"
//#include <AVStreams.idl>
//#include <bulkData.idl>

#pragma prefix "alma"

/** @file bulkDataReceiver.idl
 *  Bulk Data Receiver IDL File (Receiver Component).
 */

module bulkdataZMQ
{
    
    /** @interface BulkDataReceiver
     *  Defines the interface for the Bulk Data Receiver Component
     */
    interface BulkDataZMQReceiver : ACS::CharacteristicComponent
	{
	
	/**
	 *  @param flowNumber 
	 *  @return void
	 *  @htmlonly
	 <br><hr>
	 @endhtmlonly
	*/
	void openReceiver(in long flowNumber) raises (ACSBulkDataError::AVOpenReceiverErrorEx);


	/**
     *  @throw ACSBulkDataError::AVCloseReceiverErrorEx
     */
    void closeReceiver() raises (ACSBulkDataError::AVCloseReceiverErrorEx);

	/** 
	 *  Resets the receiver streams and flows.
	 *  @return void
	 *  @htmlonly
	 <br><hr>
	 @endhtmlonly
	*/
	void resetReceiver();
	};

};

#endif
