#!/usr/bin/env python

from Acspy.Clients.SimpleClient import PySimpleClient
from IRAPy import logger
import Management
import sys
import time

MALFORMED_XML_STRING = "aasd < !!. ...(()ASdasda,l</><\<{[[]][[[<<[{<>>}++]]]]"

client = PySimpleClient()
log_component = client.getComponent(comp_name = "MANAGEMENT/CustomLogger",
                                    comp_idl_type = "IDL:alma/Management/CustomLogger:1.0",
                                    container_name = "LoggerContainer")
try:
    log_component.emitLog(MALFORMED_XML_STRING, Management.C_INFO)
except KeyboardInterrupt:
    log_component.emitLog("malformed logging ends", Management.C_INFO)
finally:
    client.releaseComponent("MANAGEMENT/CustomLogger")

