#!/usr/bin/env python

from Acspy.Clients.SimpleClient import PySimpleClient
from IRAPy import logger
import Management
import sys

try:
    LOG_EVENTS_NUMBER = int(sys.argv[1])
except:
    LOG_EVENTS_NUMBER = 500

client = PySimpleClient()
log_component = client.getComponent(comp_name = "MANAGEMENT/CustomLogger",
                                    comp_idl_type = "IDL:alma/Management/CustomLogger:1.0",
                                    container_name = "LoggerContainer")
for i in xrange(LOG_EVENTS_NUMBER):
    log_component.emitACSLog("ACS bomb %d" % i)
    log_component.emitLog("CUSTOM bomb %d" % i, Management.C_DEBUG)
    logger.warning("Python bomb %d" % i)
    log_component.emitExceptionLog()
    log_component.emitACSExceptionLog()
log_component.emitACSLog("bombing end")
log_component.emitLog("bombing end", Management.C_DEBUG)
logger.warning("bombing end")
client.releaseComponent("MANAGEMENT/CustomLogger")
