#!/usr/bin/env python
import argparse
from SRTMSCUSimImpl import mscu

parser = argparse.ArgumentParser(description="Start/Stop the MSCU simulator")
parser.add_argument('action', choices=['start', 'stop', 'setpos_NAK', 'setpos_ACK'])
args = parser.parse_args()


if __name__ == "__main__":
    if args.action == 'start':
        server = mscu.MSCU()
        server.run()
    elif args.action == 'stop':
        mscu.MSCU.stop()
    elif args.action == 'setpos_NAK':
        mscu.MSCU.setpos_NAK()  # To default, the SRP
    elif args.action == 'setpos_ACK':  # To default, the SRP
        mscu.MSCU.setpos_ACK()
